POST http://localhost:3000/despesas
Content-Type: application/json

{
  "title": "Despesa 8",
  "amount": 100,
  "categoria": "ALIMENTACAO",
  "date": "2026-01-27T00:00:00.000Z"
}

###
GET http://localhost:3000/despesas/69f0ef80-08e3-4719-aefd-367a28685f49

###
GET http://localhost:3000/despesas?year=2025&month=4

###
PATCH http://localhost:3000/despesas/69f0ef80-08e3-4719-aefd-367a28685f49
Content-Type: application/json

{
  "title": "Despesa 1 atualizada"
}

###
DELETE http://localhost:3000/despesas/5889fbb2-83bd-4c6c-9caf-38951e0430d0